### ISSUE TITLE
404 on V2 on ramp-book.com

### ISSUE THREAD

**Issue by enricozb** [fferen/ramp-book#1]
It seems that the V2 link on [this page](http://ramp-book.com/versions.html) is broken, as is the main download link on the front page of the website. V1 looks intact.

**Comment by fferen** [comment]
That was fast! Yes, somehow the file didn't get uploaded. Should be fixed
now.

**Comment by enricozb** [comment]
Super excited to go through this. Thanks a ton for putting this together :)
